app/layout_analysis/__init__.py
from flask import Blueprint

bp = Blueprint('layout_analysis', __name__, template_folder='templates', static_folder='static')

from app.layout_analysis import routes

app/layout_analysis/routes.py
from app.layout_analysis import bp
from natsort import natsorted
from flask import escape, render_template, url_for, redirect, flash, request, current_app, send_file, abort
from flask_login import login_required, current_user
from app.db.general import get_document_by_id, get_request_by_id, get_image_by_id, get_layout_detector_by_id
from app.layout_analysis.general import create_layout_analysis_request, can_start_layout_analysis, \
    add_layout_request_and_change_document_state, get_first_layout_request, change_layout_request_and_document_state_in_progress_handler, \
    create_json_from_request, change_layout_request_and_document_state_on_success_handler, \
    change_document_state_on_complete_layout_analysis_handler, post_files_to_folder, insert_regions_to_db, \
    set_whole_page_region_layout_to_document, change_layout_request_to_fail_and_document_state_to_new_handler, \
    not_deleted_images_in_document
from app.mail.mail import send_layout_failed_mail
import os
import sys
import sqlalchemy
from app.db.model import DocumentState, RequestState, TextRegion, LayoutDetector, Document
from app.document.general import is_user_owner_or_collaborator, is_granted_acces_for_document, is_user_trusted, \
                                 document_exists, get_document_images, make_image_preview
from app import db_session
from flask import jsonify
import shutil


########################################################################################################################
# WEBSITE ROUTES
########################################################################################################################

# MENU PAGE
########################################################################################################################

@bp.route('/show_results/<string:document_id>', methods=['GET'])
@bp.route('/show_results/<string:document_id>/<string:image_id>', methods=['GET'])
@login_required
def show_results(document_id, image_id=None):
    if not document_exists(document_id):
        flash(u'Document with this id does not exist!', 'danger')
        return redirect(url_for('main.index'))
    if not is_granted_acces_for_document(document_id, current_user):
        flash(u'You do not have sufficient rights to this document!', 'danger')
        return redirect(url_for('main.index'))

    document = get_document_by_id(document_id)
    if document.state == DocumentState.NEW:
        return redirect(url_for('document.upload_images_to_document', document_id=document.id))
    elif document.state == DocumentState.COMPLETED_OCR:
        return redirect(url_for('ocr.show_results', document_id=document.id))
    elif document.state != DocumentState.COMPLETED_LAYOUT_ANALYSIS:
        flash(u'Document can not be edited in its current state.', 'danger')
        return redirect(url_for('main.index'))

    images = natsorted(get_document_images(document).all(), key=lambda x: x.filename)
    if len(images) == 0:
        flash(u'Document has not images and thus can not be viewed and edited.', 'danger')
        return redirect(url_for('main.index'))

    return render_template('layout_analysis/layout_results.html', document=document, images=images)


@bp.route('/revert_layout_analysis/<string:document_id>', methods=['GET'])
@login_required
def revert_layout(document_id):
    if not is_user_owner_or_collaborator(document_id, current_user):
        flash(u'You do not have sufficient rights to this document!', 'danger')
        return redirect(url_for('main.index'))
    print()
    print("REVERT Layout")
    print("##################################################################")
    document = Document.query.filter_by(id=document_id, deleted=False).first()
    if document.state != DocumentState.COMPLETED_LAYOUT_ANALYSIS:
        return f'Error: Unable to revert layout, document in wrong state {document.state}.', 400
    for img in document.images:
        print(img.id)
        for region in img.textregions:
            db_session.delete(region)
    document.state = DocumentState.NEW
    db_session.commit()
    print("##################################################################")
    return escape(document_id)

# SELECT PAGE
########################################################################################################################


@bp.route('/select_layout/<string:document_id>', methods=['GET'])
@login_required
def select_layout(document_id):
    if not is_granted_acces_for_document(document_id, current_user):
        flash(u'You do not have sufficient rights to this document!', 'danger')
        return redirect(url_for('main.index'))
    document = get_document_by_id(document_id)
    layout_engines = db_session.query(LayoutDetector).filter(LayoutDetector.active).order_by(LayoutDetector.order).all()
    return render_template('layout_analysis/layout_select.html', document=document, layout_engines=layout_engines)


@bp.route('/start_layout/<string:document_id>', methods=['POST'])
@login_required
def start_layout(document_id):
    if not is_granted_acces_for_document(document_id, current_user):
        flash(u'You do not have sufficient rights to this document!', 'danger')
        return redirect(url_for('main.index'))
    document = get_document_by_id(document_id)
    if not not_deleted_images_in_document(document):
        flash(u'Can\'t create request without uploading images.', 'danger')
        return redirect(request.referrer)
    layout_detector_id = request.form['layout_detector_id']
    layout_detector = get_layout_detector_by_id(layout_detector_id)
    layout_detector_name = get_layout_detector_folder_name(layout_detector.name)
    if layout_detector_name == "none":
        change_document_state_on_complete_layout_analysis_handler(document)
    elif layout_detector_name == "whole_page_region":
        set_whole_page_region_layout_to_document(document)
        change_document_state_on_complete_layout_analysis_handler(document)
    else:
        layout_request = create_layout_analysis_request(document, layout_detector_id)
        if can_start_layout_analysis(document):
            add_layout_request_and_change_document_state(layout_request)
            flash(u'Request for layout analysis successfully created!', 'success')
        else:
            flash(u'Request for layout analysis is already pending or document is in unsupported state!', 'danger')
    return redirect(url_for('document.documents'))


# RESULTS PAGE
########################################################################################################################

@bp.route('/edit_layout/<string:image_id>', methods=['POST'])
@login_required
def edit_layout(image_id):
    try:
        db_image = get_image_by_id(image_id)
    except sqlalchemy.exc.StatementError:
        return "Image does not exist.", 404
    
    document_id = db_image.document_id
    if not is_granted_acces_for_document(document_id, current_user):
        return 'You do not have sufficient rights to this document!', 403
    regions = request.get_json()
    existing_regions = dict([(str(region.id), region) for region in db_image.textregions])
    for region in regions:
        if not region or 'points' not in region or len(region['points']) <= 2:
            continue
        points = region['points']
        if region['uuid'] not in existing_regions:
            db_region = TextRegion(id=region['uuid'], deleted=region['deleted'], image_id=image_id, order=region['order'])
            db_region.np_points = points
            db_image.textregions.append(db_region)
        else:
            db_region = existing_regions[region['uuid']]
            db_region.np_points = points
            db_region.deleted = region['deleted']
            db_region.order = region['order']
    try:
        db_session.commit()
        make_image_preview(db_image)
    except sqlalchemy.exc.IntegrityError as err:
        print('ERROR: Unable to save text regions.', err, file=sys.stderr)
        db_session.rollback()
        return 'Failed to save.', 420
    return 'OK'


########################################################################################################################
# CLIENT ROUTES
########################################################################################################################

# POST RESPONSE FROM CLIENT, XMLS
########################################################################################################################

@bp.route('/post_result/<string:request_id>/<string:image_id>', methods=['POST'])
@login_required
def post_result(request_id, image_id):
    if not is_user_trusted(current_user):
        flash(u'You do not have sufficient rights!', 'danger')
        return redirect(url_for('main.index'))

    db_request = get_request_by_id(request_id)
    if db_request.state != RequestState.IN_PROGRESS:
        return "Request in wrong state: {}.".format(db_request.state), 406

    try:
        image = get_image_by_id(image_id)
    except sqlalchemy.exc.StatementError:
        return "Image does not exist.", 404

    if image.document.state != DocumentState.COMPLETED_LAYOUT_ANALYSIS:
        print()
        print("INSERT REGIONS FROM XMLS TO DB")
        print("##################################################################")
        result_folder = os.path.join(current_app.config['LAYOUT_RESULTS_FOLDER'], str(image.document_id))
        if not os.path.exists(result_folder):
            os.makedirs(result_folder, exist_ok=True) # exist_ok=True is needed due to multi-processing
        file_names = post_files_to_folder(request, result_folder)
        insert_regions_to_db(result_folder, file_names)
        print("##################################################################")
    return 'OK'


@bp.route('/change_layout_request_and_document_state_on_success/<string:request_id>', methods=['POST'])
@login_required
def change_layout_request_and_document_state_on_success(request_id):

app/templates/layout_analysis/layout_results.html
{% extends "base/base.html" %}
{% block content %}
    <div class="container-fluid px-4">

        <div class="row my-4">
            <div class="col-sm-8">
                <h3 class="text-left">Document name: {{ document.name }}</h3>
            </div>
            <div class="col-sm-4 text-right" >
                {% include '/document/document_action_buttons.html' %}
            </div>
        </div>

        <div class="row mb-4">
            <div class="col-sm-12">
                {% include 'base/scrolling_wrapper.html' %}
            </div>
        </div>

        <div class="row mb-2">
            <div class="col-xl-3 mb-2">
                <button id="back-btn" class="btn btn-secondary"><i class="fas fa-arrow-left"></i>&nbsp;&nbsp;Back&nbsp;(b)</button>
                <button id="next-btn" class="btn btn-secondary">Next&nbsp;(n)&nbsp;&nbsp;<i class="fas fa-arrow-right"></i></button>
            </div>
            <div class="col-xl-6 mb-2 text-xl-center">
                <button id="create-new-object-btn" class="btn btn-secondary"><i class="fas fa-plus fa-lg"></i>&nbsp;&nbsp;New&nbsp;object&nbsp;(c)</button>
                <button id="toggle-delete-object-btn"class="btn btn-secondary"><i class="fas fa-times fa-lg"></i>&nbsp;&nbsp;Toggle&nbsp;delete&nbsp;(g)</button>
                <button id="toggle-delete-all-objects-btn" class="btn btn-secondary"><i class="fas fa-times fa-lg"></i>&nbsp;&nbsp;Toggle&nbsp;delete&nbsp;all&nbsp;(a)</button>
                <button id="reset-btn"class="btn btn-secondary"><i class="fas fa-redo-alt fa-lg"></i>&nbsp;&nbsp;Reset&nbsp;(r)</button>
            </div>
            <div class="col-xl-3 text-xl-right">
                <button id="save-image-btn" class="btn btn-success"><i class="far fa-save fa-lg"></i>&nbsp;&nbsp;Save&nbsp;(s)</button>
                <a id="btn-export-page-xml" class="btn btn-info" role="button" download><i class="far fa-file-code fa-lg"></i>&nbsp;&nbsp;Export PAGE</a>
                <a id="btn-export-img" class="btn btn-info" role="button" download><i class="far fa-file-image fa-lg"></i></i>&nbsp;&nbsp;Export IMAGE</a>
            </div>
        </div>

        <div class="row">
            <div class="col">
                <div class="current-result-container" data-document="{{ document.id }}" data-image="{{ images[0].id }}">
                    <div id="map-container">
                        <div id="mapid"></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row my-2">
            <div class="col-xl-4">
                <div class="d-flex flex-row">
                    <p id="status"></p>
                </div>
            </div>
            <div class="col-xl-4 d-none d-xl-block text-center">
                <div class="btn-group-toggle" data-toggle="buttons">
                    <label id="showOrderWrapper" class="btn btn-secondary">
                        <input type="checkbox" name="show-reading-order-btn" autocomplete="off"><span> Show reading order (w)</span>
                    </label>
                    <label id="setOrderWrapper" class="btn btn-secondary">
                        <input type="checkbox" name="set-reading-order-btn" autocomplete="off"><span> Set reading order (e)</span>
                    </label>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="/static/leaflet/leaflet.css">
    <link rel="stylesheet" href="/static/css/LayoutResults.css">
{% endblock %}

{% block scripts %}
    <script src="{{ url_for('static', filename='js/lazy_image.js') + '?version=0.0.1' }}"></script>
    <script>
        document.addEventListener("DOMContentLoaded",
            function () {
                manage_lazy_images(template_set_url_callback)
            });
    </script>

    <script src="/static/leaflet/leaflet.js"></script>
    <script src="/static/leaflet/Leaflet.Editable.js"></script>
    <script src="/static/leaflet/Path.Drag.js"></script>
    <script src="/static/js/layout/lp_object.js?version=1.4.2"></script>
    <script src="/static/js/layout/pl_order.js?version=1.4.2"></script>
    <script src="/static/js/layout/layout_editor.js?version=1.4.2"></script>
    <script src="/static/js/layout/layout_export_buttons.js?version=1.4.3"></script>
    <script src="/static/js/image_list.js?version=1.4.4"></script>
    <script>
        let layout_export_buttons = new LayoutExportButtons();
        var layout_editor = new LayoutEditor();
        let image_list = new ImageList([layout_export_buttons, layout_editor]);

        document.querySelector('body').addEventListener('keydown', shortcut);
        function shortcut(e) {
            var code = e.which || e.keyCode;
            switch (code) {
                case 66: // b
                    image_list.previous_image();
                    break;
                case 78: // b
                    image_list.next_image();
                    break;
                case 67: // c
                    if (layout_editor.create_new_object_btn.disabled == false){
                        layout_editor.create_new_object();
                    }
                    break;
                case 71: // g
                    if (layout_editor.toggle_delete_object_btn.disabled == false){
                        layout_editor.toggle_delete_object();
                    }
                    break;
                case 65: // a
                    if (layout_editor.toggle_delete_all_objects_btn.disabled == false){
                        layout_editor.toggle_delete_all_objects();
                    }
                    break;
                case 82: // r
                    layout_editor.reset_image();
                    break;
                case 83:  // s
                    layout_editor.save_image();
                    break;
                case 87: // w
                    if (layout_editor.show_reading_order_btn.checked == false){
                        layout_editor.enable_show_order();
                        layout_editor.show_reading_order();
                    }
                    else {
                        layout_editor.disable_show_order();
                        layout_editor.show_reading_order();
                    }
                    break;
                case 69: // e
                    if (layout_editor.set_reading_order_btn.checked == false){
                        layout_editor.enable_set_order();
                        layout_editor.set_reading_order();
                    }
                    else {
                        layout_editor.disable_set_order();
                        layout_editor.set_reading_order();
                    }
                    break;
                case 27: // Escape
                    layout_editor.unselect_objects()
            }
        }
    </script>
{% endblock %}

app/templates/layout_analysis/layout_select.html
{% extends "base/base.html" %} {% block content %}
    <div class="container-fluid px-4">

        <div class="row mt-4">
            <div class="offset-xl-2 col-xl-10 offset-lg-1 col-lg-11">
                <h3 class="text-left">{{ document.name }} - Start Layout Analysis</h3>
            </div>
        </div>

        <form action="{{ url_for('layout_analysis.start_layout', document_id=document.id) }}" method="POST">

            <div class="row mt-4">
                <div class="offset-xl-2 col-xl-10 offset-lg-1 col-lg-11">
                    <h5 class="text-left">Select layout detector</h5>
                </div>
            </div>
            <div class="row">
                <div class="offset-xl-2 col-xl-5 offset-lg-1 col-lg-6">
                <select class="form-control" name="layout_detector_id" style="width:100%">
                    {% for layout_detector in layout_engines %}
                    <option value="{{ layout_detector.id }}" model-type-description="layout-detector-description"
                            data-description="{{ layout_detector.description }}" {{ "selected" if layout_detector.id == "387784dc-d476-4c6f-9f95-7bf1081d5600" }}>
                        {{layout_detector.name}}</option>
                    {% endfor %}
                </select>
                </div>
            </div>
            <div class="row mt-2">
                <div class="offset-xl-2 col-xl-5 offset-lg-1 col-lg-6 text-justify" id="layout-detector-description">
                </div>
            </div>

            <div class="row">
                <div class="offset-xl-2 col-xl-10 offset-lg-1 col-lg-11">
                    <input class="btn btn-primary my-3" type="submit" value="Submit">
                </div>
            </div>

        </form>

    </div>
{% endblock %}

{% block scripts %}
    <script src="/static/js/select.js?version=1.1"></script>
{% endblock %}

app/templates/layout_analysis/start_layout.html
{% extends "base/base.html" %} {% block content %}
    <div>
        <h3 class="text-left">{{ document.name }} - Start Layout Analysis</h3>
        <form action="{{ url_for('layout_analysis.start_layout_analysis_post', document_id=document.id) }}" method="POST">
            <select class="js-example-basic-single" name="layout_analysis_type" style="width:100%">
                <option value="NO_LAYOUT">No Layout Analysis</option>
                <option value="BASIC">Basic Layout Analysis</option>
            </select>
            <input class="btn btn-primary my-3" type="submit" value="Submit">
        </form>

    </div>
{% endblock %} {% block styles %}
<link href="/static/select2/select2.min.css" rel="stylesheet" />
{% endblock %}

{% block scripts %}
    <script src="/static/select2/select2.min.js"></script>
    <script>

    </script>
{% endblock %}