app/document/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired


class CreateDocumentForm(FlaskForm):
    document_name = StringField('Document Name', validators=[DataRequired()])
    submit = SubmitField('Create')

app/document/__init__.py
from flask import Blueprint

bp = Blueprint('document', __name__, template_folder='templates', static_folder='static')

from app.document import routes

app/document/routes.py
import _thread
from email.policy import default

import sqlalchemy

from app.document import bp
from flask_login import login_required, current_user
from flask import render_template, redirect, url_for, request, send_file, flash, jsonify
from flask import current_app, escape, Response
from app.document.general import create_document, check_and_remove_document, save_image, \
    get_collaborators_select_data, save_collaborators, is_document_owner, is_user_owner_or_collaborator,\
    remove_image, get_document_images, get_page_layout, get_page_layout_text, update_confidences, is_user_trusted,\
    is_granted_acces_for_page, is_granted_acces_for_document, get_line_image_by_id, get_sucpect_lines_ids, \
    compute_scores_of_doc, skip_textline, get_line, is_granted_acces_for_line, create_string_response, \
    update_baselines, make_image_preview, find_textlines, get_documents_with_granted_acces, \
    check_and_change_public_document, is_document_public, get_processed_pages_counter

from werkzeug.exceptions import NotFound

from app.db.general import get_requests

from app.db.general import get_user_documents, get_document_by_id, get_user_by_email, get_all_documents,\
                           get_previews_for_documents, get_image_by_id, get_public_documents
from app.document.forms import CreateDocumentForm
from app.document.annotation_statistics import get_document_annotation_statistics, get_user_annotation_statistics, get_document_annotation_statistics_by_day
from io import BytesIO
import dateutil.parser
import zipfile
import time
import os
import json
import re
from natsort import natsorted

from pero_ocr.core.layout import logger


@bp.route('/documents')
@login_required
def documents():
    if is_user_trusted(current_user):
       user_documents = get_all_documents()
    else:
       user_documents = get_user_documents(current_user)

    user_documents = sorted(user_documents, key=lambda x: x.created_date)[::-1]
    document_ids = [d.id for d in user_documents]
    previews = dict([(im.document_id, im) for im in get_previews_for_documents(document_ids)])

    processed_pages_counter = {}
    for d in user_documents:
        if d.id not in previews:
            previews[d.id] = ""
        processed_pages_counter[d.id] = get_processed_pages_counter(d)

    return render_template('document/documents.html', documents=user_documents, previews=previews,
                           processed_pages_counter=processed_pages_counter)


@bp.route('/user_documents')
@login_required
def documents_user():
    trusted_user = False
    if is_user_trusted(current_user):
       user_documents = get_all_documents()
       trusted_user = True
    else:
       user_documents = get_user_documents(current_user)

    user_documents = sorted(user_documents, key=lambda x: x.created_date)[::-1]
    user_documents_json = []
    for user_document in user_documents:
        is_owner_tmp = user_document.user_id == current_user.id
        if trusted_user:
            is_owner_tmp = True
        user_documents_json.append({
            'id': user_document.id,
            'name': user_document.name,
            'state': user_document.state.value,
            'line_count': user_document.line_count,
            'annotated_line_count': user_document.annotated_line_count,
            'created_date': user_document.created_date,
            'is_public': user_document.is_public,
            'owner_id': user_document.user_id,
            'owner_name': user_document.user.first_name + ' ' + user_document.user.last_name,
            'owner_username': user_document.user.email,
            'owner_institution': user_document.user.institution,
            'is_owner': is_owner_tmp
        })
    return Response(json.dumps(user_documents_json, default=str),  mimetype='application/json')


@bp.route('/is_owner/<string:document_id>')
@login_required
def is_owner(document_id):
    if is_user_trusted(current_user):
       return Response(json.dumps({'is_owner': True}),  mimetype='application/json')
    document = get_document_by_id(document_id)
    if document.user_id == current_user.id:
        return Response(json.dumps({'is_owner': True}),  mimetype='application/json')
    return Response(json.dumps({'is_owner': False}),  mimetype='application/json')


@bp.route('/public_documents')
def public_documents():
    db_documents = get_public_documents()
    document_ids = [d.id for d in db_documents]
    previews = dict([(im.document_id, im) for im in get_previews_for_documents(document_ids)])

    for d in db_documents:
        if d.id not in previews:
            previews[d.id] = ""

    return render_template('document/public_documents.html', documents=db_documents, previews=previews)


@bp.route('/annotation_statistics/<string:document_id>')
@login_required
def annotation_statistics(document_id):
    if not (is_user_owner_or_collaborator(document_id, current_user) or is_user_trusted(current_user)):
        flash(u'You do not have sufficient rights to view statistics for this document!', 'danger')
        return redirect(url_for('main.index'))

    document = get_document_by_id(document_id)
    statistics = get_document_annotation_statistics(document)

    return render_template('document/annotation_statistics.html', statistics=statistics, header_name=document.name)


@bp.route('/annotation_statistics')
@login_required
def annotation_statistics_global():
    if not is_user_trusted(current_user):
        flash(u'You do not have sufficient rights to view global statistics!', 'danger')
        return redirect(url_for('main.index'))

    statistics = get_document_annotation_statistics()

    return render_template('document/annotation_statistics.html', statistics=statistics, header_name='All documents')


@bp.route('/user_annotation_statistics/<string:user_email>')
@login_required
def user_annotation_statistics(user_email):
    if not is_user_trusted(current_user):
        flash(u'You do not have sufficient rights to view statistics for other users!', 'danger')
        return redirect(url_for('main.index'))

    user = get_user_by_email(user_email)
    statistics = get_user_annotation_statistics(user)

    return render_template('document/annotation_statistics.html',
                           statistics=statistics, header_name=f'{user.first_name} {user.last_name}')


@bp.route('/user_annotation_statistics')
@login_required
def user_annotation_statistics_current_user():
    statistics = get_user_annotation_statistics(current_user)

    return render_template('document/annotation_statistics.html',
                           statistics=statistics, header_name=f'{current_user.first_name} {current_user.last_name}')


@bp.route('/user_annotation_statistics_global')
@login_required
def user_annotation_statistics_global():
    if not is_user_trusted(current_user):
        flash(u'You do not have sufficient rights to view statistics for other users!', 'danger')
        return redirect(url_for('main.index'))

    statistics = get_user_annotation_statistics()

    return render_template('document/annotation_statistics.html', statistics=statistics, header_name='All users')


@bp.route('/requests')
@login_required
def requests():
    if is_user_trusted(current_user):
       user_documents = get_all_documents()
    else:
       user_documents = get_user_documents(current_user)

    document_ids = [d.id for d in user_documents]
    requests = get_requests(document_ids)

    return render_template('requests/request_list.html', requests=requests)


@bp.route('/document_history/<string:document_id>')
@login_required
def document_history(document_id):
    if not (is_user_owner_or_collaborator(document_id, current_user) or is_user_trusted(current_user)):
        flash(u'You do not have sufficient rights to view statistics for this document!', 'danger')
        return redirect(url_for('main.index'))

    db_requests = get_requests(document_ids=[document_id])
    db_document = get_document_by_id(document_id)

    ann_stats = get_document_annotation_statistics_by_day(db_document.id)

    import altair as alt
    data = [{'x': str(date), 'y': count, 'u': f'{user1} {user2}'} for date, user1, user2, count in ann_stats]
    data = alt.Data(values=data)
    chart = alt.Chart(data).mark_bar().encode(
            x='x:T',  # specify ordinal data
            y='sum(y):Q',  # specify quantitative data
            color='u:N'
        ).properties(width='container', height=300)

    return render_template('document/document_history.html',
                           requests=db_requests, document=db_document, graph_json=chart.to_json(indent=0))



@bp.route('/new_document', methods=['GET', 'POST'])
@login_required
def new_document():
    form = CreateDocumentForm()
    if form.validate_on_submit():
        document = create_document(form.document_name.data, current_user)
        flash(u'Document successfully created!', 'success')
        return redirect(url_for('document.upload_images_to_document', document_id=document.id))
    else:
        return render_template('document/new_document.html', form=form)


@bp.route('/make_public/<string:document_id>')
@login_required
def make_public(document_id):
    document_name = check_and_change_public_document(document_id, current_user, True)
    if document_name:
        flash(f'Document "{document_name}" in now public!', 'success')
        return escape(document_id)
    else:
        flash(u'You do not have sufficient rights to make this document public!', 'danger')
        return None


@bp.route('/make_private/<string:document_id>')
@login_required
def make_private(document_id):
    document_name = check_and_change_public_document(document_id, current_user, False)
    if document_name:
        flash(f'Document "{document_name}" in now private!', 'success')
        return escape(document_id)
    else:
        flash(u'You do not have sufficient rights to make this document public!', 'danger')
        return None

app/templates/document/annotation_statistics.html
{% extends "base/base.html" %}
{% block content %}
    <div class="container-fluid px-4">
        <div class="row my-4">
            <div class="col-sm-12">
                <h3 class="text-left">{{ header_name }} - Annotation statistics</h3>
            </div>
        </div>
        <div class="row">
            <div class="offset-xl-1 col-xl-10">
                <table id="document_table" class="table table-hover">
                    <thead>
                    <tr role="row">
                        <th scope="col">User</th>
                        <th scope="col">Lines</th>
                        <th scope="col">Changed lines</th>
                        <th scope="col">Characters</th>
                        <th scope="col">Changes</th>
                        <th scope="col">Time</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for stat in statistics %}
                        <tr data-document="{{ request.id }}">
                            <td>{{ stat['user'] }}</td>
                            <td>{{ stat['lines'] }}</td>
                            <td>{{ stat['changed_lines'] }}</td>
                            <td>{{ stat['characters'] }}</td>
                            <td>{{ stat['changed_characters'] }}</td>
                            <td>{{ stat['time'] }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="/static/css/loader.css?v=1.0">
{% endblock %}

{% block scripts %}
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>
    <script>
        $(document).ready(function () {
            // Setup table - add a text input to each footer cell
            $('#document_table thead tr').clone(true).appendTo('#document_table thead');
            table = $('#document_table').DataTable({
                stateSave: true,
                orderCellsTop: true,
                fixedHeader: true
            });
            var state = table.state.loaded();
            $('#document_table thead tr:eq(1) th').each(function (i) {
                var input_value = '';
                try {
                    input_value = state.columns[i].search.search;
                } catch(err){
                    console.log('ERROR')
                }
                $(this).html('<input type="text" placeholder="Search"  value="' + input_value + '"/>');
                $('input', this).on('keyup change', function () {
                    if (table.column(i).search() !== this.value) {
                        table.column(i).search(this.value).draw();
                    }
                });
            });
        });
    </script>
{% endblock %}

app/templates/document/document_action_buttons.html
{% if document.user.id == current_user.id or current_user.trusted == 1 %}
<a  class="document-action-btn btn btn-secondary"
    href="{{ url_for('document.collaborators_get', document_id=document.id) }}"
    data-toggle="tooltip"
    data-placement="right"
    title="Edit Collaborators">
    <i class="fas fa-users fa-fw"></i>
</a>
{% endif %}

{% if document.state.name == 'NEW' %}
<a  class="document-action-btn btn btn-secondary"
    href="{{ url_for('document.upload_images_to_document', document_id=document.id) }}"
    data-toggle="tooltip"
    data-placement="right"
    title="Upload Images">
    <i class="fas fa-cloud-upload-alt fa-fw"></i>
</a>
<a  class="document-action-btn btn btn-secondary text-white"
    href="{{ url_for('layout_analysis.select_layout', document_id=document.id) }}"
    data-toggle="tooltip"
    data-placement="right"
    title="Run layout analysis">
    <i class="fas fa-forward fa-fw"></i>
</a>
{% endif %}

{% if document.state.name == 'COMPLETED_LAYOUT_ANALYSIS' %}
<a  class="document-action-btn btn btn-secondary text-white"
    href="{{ url_for('layout_analysis.show_results', document_id=document.id) }}"
    data-toggle="tooltip"
    data-placement="right"
    title="Open document">
    <i class="fas fa-eye fa-fw"></i>
</a>
<a  class="document-action-btn btn btn-secondary text-white"
    href="{{ url_for('document.document_history', document_id=document.id) }}"
    data-toggle="tooltip"
    data-placement="right"
    title="Document history">
    <i class="fas fa-info fa-fw"></i>
</a>
<a  class="document-action-btn btn btn-secondary text-white"
    href="{{ url_for('ocr.select_ocr', document_id=document.id) }}"
    data-toggle="tooltip"
    data-placement="right"
    title="Run OCR">
    <i class="fas fa-forward fa-fw"></i>
</a>
    {% if document.user.id == current_user.id or current_user.trusted == 1 %}
    <a  class="document-action-btn btn btn-secondary text-white revert-layout-button"
        data-toggle="tooltip"
        data-placement="right"
        title="Revert layout analysis"
        data-document="{{ document.id }}">
        <i class="fas fa-backward"></i>
    </a>
    {% endif %}
{% endif %}

{% if document.state.name == 'COMPLETED_OCR' %}
<a  class="document-action-btn btn btn-secondary text-white"
    href="{{ url_for('ocr.show_results', document_id=document.id) }}"
    data-toggle="tooltip"
    data-placement="right"
    title="Open document">
    <i class="fas fa-eye fa-fw"></i>
</a>
<a  class="document-action-btn btn btn-secondary text-white"
    href="{{ url_for('document.document_history', document_id=document.id) }}"
    data-toggle="tooltip"
    data-placement="right"
    title="Document history">
    <i class="fas fa-info fa-fw"></i>
</a>
<a  class="document-action-btn btn btn-secondary text-white"
    href="{{ url_for('ocr.select_ocr', document_id=document.id) }}"
    data-toggle="tooltip"
    data-placement="right"
    title="Run OCR">
    <i class="fas fa-forward fa-fw"></i>
</a>
<a  class="document-action-btn btn btn-secondary text-white"
    href="{{ url_for('document.get_document_pages', document_id=document.id) }}"
    data-toggle="tooltip"
    data-placement="right"
    title="Download all transcriptions">
    <i class="fas fa-file-download fa-fw"></i>
</a>
<a  class="document-action-btn btn btn-secondary text-white"
    href="{{ url_for('document.annotation_statistics', document_id=document.id) }}"
    data-toggle="tooltip"
    data-placement="right"
    title="Statistics">
    <i class="fas fa-chart-line fa-fw"></i>
</a>
    {% if document.user.id == current_user.id or current_user.trusted == 1 %}
    <a  class="document-action-btn btn btn-secondary text-white revert-OCR-button"
        data-toggle="tooltip"
        data-placement="right"
        title="Revert OCR"
        data-document="{{ document.id }}">
        <i class="fas fa-backward"></i>
    </a>
    {% endif %}

{% endif %}


{% if document.user.id == current_user.id %}
    <a class="document-action-btn btn btn-secondary text-white delete-document-button"
       data-toggle="tooltip"
       data-placement="right"
       title="Remove Document"
       data-document="{{ document.id }}">
        <i class="fas fa-trash fa-fw"></i>
    </a>
{% endif %}

{% if document.user.id == current_user.id %}
    {% if document.is_public%}
        <a class="document-action-btn btn btn-secondary text-white make-private-button"
           data-toggle="tooltip"
           data-placement="right"
           title="Make document private"
           data-document="{{ document.id }}">
            <i class="fas fa-user-times fa-fw"></i>
        </a>
    {% else %}
      <a class="document-action-btn btn btn-secondary text-white make-public-button"
           data-toggle="tooltip"
           data-placement="right"
           title="Make document public"
           data-document="{{ document.id }}">
            <i class="fas fa-user-plus fa-fw"></i>
        </a>
    {% endif %}
{% endif %}

app/templates/document/document_history.html
{% extends "base/base.html" %}
{% block content %}

    <div class="container-fluid px-4">
        <div class="row">
            <div class="col-sm-6">
                <h3 class="text-left">Document name: {{ document.name }}</h3>
                <h3 id="document-id" style="display: None">{{ document.id }}</h3>
            </div>
            <div class="col-sm-4 text-right" >
                {% include '/document/document_action_buttons.html' %}
            </div>
        </div>
        <div class="row">
            <div id="vis" class="offset-xl-1 col-xl-10">
            </div>
        </div>
        <div class="row">
            <div class="offset-xl-1 col-xl-10">
                <table id="request_table" class="table table-hover">
                    <thead>
                    <tr role="row">
                        <th scope="col">Date</th>
                        <th scope="col">Job State</th>
                        <th scope="col">Job Type</th>
                        <th scope="col">Models</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for request in requests %}
                        <tr data-document="{{ request.id }}">
                            <td class="utc-time" data-sort="{{loop.index}}">{{ request.created_date.isoformat() }}</td>
                            <td>{{ request.state.name }}</td>
                            <td>{{ request.request_type.name }}</td>
                            <td>{{ request.layout_detector.name if request.layout_detector.name else "---"}}, {{ request.baseline.name if request.baseline.name else "---"}}, {{ request.ocr.name if request.ocr.name else "---" }}, {{ request.language_model.name if request.language_model.name else "---" }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="/static/css/loader.css?v=1.0">
    <style>
        .document-action-btn{
            min-height: 25px;
        }
    </style>
{% endblock %}

{% block scripts %}
    <script src="https://cdn.jsdelivr.net/npm/vega@5"></script>
    <script src="https://cdn.jsdelivr.net/npm/vega-lite@5"></script>
    <script src="https://cdn.jsdelivr.net/npm/vega-embed@6"></script>
    <script>
        $(document).ready(function () {
            var spec = {{ graph_json|safe }};
            var opt = {"renderer": "canvas", "actions": false};
            vegaEmbed("#vis", spec, opt);
            // Setup table - add a text input to each footer cell
        });

        for(var elem of document.getElementsByClassName("utc-time")){
            const date = new Date(elem.textContent + 'Z');
            elem.innerHTML = date.toLocaleString();
        }
    </script>
{% endblock %}

app/templates/document/edit_collaborators.html
{% extends "base/base.html" %}
{% block content %}

    <div class="container-fluid px-4">

        <div class="row mt-4">
            <div class="offset-xl-2 col-xl-10">
                <h3>{{ document.name }} - Edit Collaborators</h3>
            </div>
        </div>

        <div class="row">
            <div class="offset-xl-2 col-xl-8">
                <form action="{{ url_for('document.collaborators_post', document_id=document.id) }}" method="POST">
                    <select class="js-example-basic-single" name="collaborators" multiple="multiple" style="width:100%">
                        {% for collaborator in  collaborators %}
                            <option {% if collaborator.is_selected != None %} selected {% endif %} value="{{ collaborator.user.id }}">{{collaborator.user.first_name }} {{ collaborator.user.last_name }} ({{ collaborator.email_an }})</option>
                        {% endfor %}
                    </select>
                <input class="btn btn-primary my-3" type="submit" value="Submit">
                </form>
            </div>
        </div>

    </div>

{% endblock %}


{% block scripts%}

<link href="/static/select2/select2.min.css" rel="stylesheet" />
<script src="/static/select2/select2.min.js"></script>
<script>
$(document).ready(function() {
  $('.js-example-basic-single').select2({
    placeholder: 'Select Collaborators'
  });
});
</script>

{% endblock %}

app/templates/document/new_document.html
{% import  "bootstrap/wtf.html" as wtf %}
{% extends "base/base.html" %}
{% block content %}
    <div class="container-fluid">

        <div class="row mt-4">
            <div class="offset-xl-2 col-xl-10">
                <h3>New Document</h3>
            </div>
        </div>

        <div class="row">
            <div class="offset-xl-2 col-xl-8">
                {{ wtf.quick_form(form) }}
            </div>
        </div>

    </div>
{% endblock %}

app/templates/document/public_documents.html
{% extends "base/base.html" %}
{% block content %}
    <section class="jumbotron text-center">
        <div class="container">
          <h1 class="jumbotron-heading">Public documents</h1>
          <p class="lead text-muted">These documents were uploaded by the users of pero-ocr.</p>
        </div>
    </section>
    <div class="album py-5 bg-light">
        <div class="container">
          <div class="row">
            {% for document in documents %}
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <img data-src="{{url_for('document.get_public_image_preview', image_id=previews[document.id].id)}}" class="card-img-top lazy-img" src="" onerror="this.src='/static/img/missing_page.png'"/>
                  <div class="card-body">
                    <h5 class="card-title">{{ document.name }}</h5>
                    <!-- p class="card-text">
                    </p -->
                    <a href="{{ url_for('ocr.show_public_results', document_id=document.id) }}" class="btn btn-primary">View document</a>
                  </div>
                </div>
            </div>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
{% endblock %}

{% block styles %}
{% endblock %}

{% block scripts %}
    <script src="{{ url_for('static', filename='js/lazy_image.js') + '?version=0.0.1' }}"></script>
    <script>
        document.addEventListener("DOMContentLoaded",
            function () {
                manage_lazy_images(template_set_url_callback)
            });
    </script>
{% endblock %}

app/templates/document/search_lines.html
{% extends "base/base.html" %}

{% block content %}
    <div class="container-fluid px-4">
        <div class="row my-4">
            <div class="col-sm-12">
                <h3 class="text-left">Text line search</h3>
                <div id="document-id" style="display: none"></div>
            </div>
        </div>

        <form method="POST">
            <label for="documents">Documents</label>
            <div class="row" style="margin-left: 0px; margin-right: 0px; margin-bottom: 10px;">
                <select id="documents" class="js-example-basic-single" name="documents" multiple="multiple" style="width:100%">
                    {% for i, document in  documents %}
                        <option {% if selected[i] == True %} selected {% endif %} value="{{ document.id }}">{{document.name}} ({{ document.id }})</option>
                    {% endfor %}
                </select>
            </div>
            <label for="query">Query</label>
            <div class="input-group">
                <input id="query" type="text" class="form-control" name="query" placeholder="Query" value="{{ query }}">
              <span class="input-group-btn">
                <input class="btn btn-primary" type="submit" value="Search"/>
              </span>
            </div>
        </form>

        {%for line in lines%}
            <div class="card" style="margin-top: 10px;">
              <a href="/ocr/show_results/{{ line.document_id }}/{{ line.image_id }}/{{ line.id }}" target="_blank"><img loading="lazy" class="line_image card-img-top" src="..." alt="Textline"></a>
              <div class="card-body">
                <p class="card-text">{{ line.text }}</p>
              </div>
            </div>
            <li style="display: none" class="line">{{ line.id }}</li>
        {%endfor%}
    </div>
{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="/static/leaflet/leaflet.css">
    <link rel="stylesheet" href="/static/css/ocr_results.css">
{% endblock %}

{% block scripts %}
    <script src="/static/leaflet/leaflet.js"></script>
    <script src="/static/leaflet/Leaflet.Editable.js"></script>
    <script src="/static/leaflet/Path.Drag.js"></script>
    <script>
        let lines = document.getElementsByClassName("line");
        let lines_images = document.getElementsByClassName("line_image");

        for (let i = 0; i < lines.length; i++){
            lines_images[i].setAttribute("src", Flask.url_for('document.get_cropped_image', {'line_id': lines[i].innerHTML}));
        }
    </script>
    <link href="/static/select2/select2.min.css" rel="stylesheet" />
    <script src="/static/select2/select2.min.js"></script>
    <script>
    $(document).ready(function() {
      $('.js-example-basic-single').select2({
        placeholder: 'Documents'
      });
    });
    </script>
{% endblock %}