app/ocr/__init__.py
from flask import Blueprint

bp = Blueprint('ocr', __name__, template_folder='templates', static_folder='static')

from app.ocr import routes

app/ocr/routes.py
import os
import shutil
import json
import uuid
from collections import defaultdict
from natsort import natsorted
import copy
import sqlalchemy
import unicodedata
from pero_ocr.core.arabic_helper import ArabicHelper
from flask import render_template, request, current_app, send_file
from flask import url_for, redirect, flash, jsonify
from flask_login import login_required, current_user
from app.ocr import bp
from app.db.general import get_document_by_id, get_request_by_id, get_image_by_id, get_baseline_by_id, get_ocr_by_id, \
                           get_language_model_by_id, get_text_line_by_id, get_text_region_by_id, get_image_annotation_statistics_db, \
                           get_document_annotation_statistics_db, get_previews_for_documents, TextLine
from app.db import DocumentState, RequestState, OCR, Document, Image, TextRegion, Baseline, LanguageModel, User, OCRTrainingDocuments
from app.ocr.general import create_json_from_request, create_ocr_request, \
                            can_start_ocr, add_ocr_request_and_change_document_state, get_first_ocr_request, \
                            insert_lines_to_db, change_ocr_request_and_document_state_on_success_handler, insert_annotations_to_db, \
                            update_text_lines, get_page_annotated_lines, change_ocr_request_and_document_state_in_progress_handler, \
                            post_files_to_folder, change_ocr_request_to_fail_and_document_state_to_success_handler, \
                            change_ocr_request_to_fail_and_document_state_to_completed_layout_analysis_handler, set_delete_flag, \
                            set_training_flag
from app.mail.mail import send_ocr_failed_mail

from app.document.general import get_document_images
from app import db_session, engine
from app.db import Image
from app.document.general import is_user_owner_or_collaborator, is_user_trusted, is_granted_acces_for_page, \
                                 is_granted_acces_for_document, is_score_computed, document_exists, \
                                 document_in_allowed_state


########################################################################################################################
# WEBSITE ROUTES
########################################################################################################################

# MENU PAGE
########################################################################################################################

@bp.route('/show_results/<string:document_id>', methods=['GET'])
@bp.route('/show_results/<string:document_id>/<string:image_id>', methods=['GET'])
@bp.route('/show_results/<string:document_id>/<string:image_id>/<string:line_id>', methods=['GET'])
@login_required
def show_results(document_id, image_id=None, line_id=None):
    if not document_exists(document_id):
        flash(u'Document with this id does not exist!', 'danger')
        return redirect(url_for('main.index'))
    if not is_user_owner_or_collaborator(document_id, current_user):
        flash(u'You do not have sufficient rights to this document!', 'danger')
        return redirect(url_for('main.index'))

    document = get_document_by_id(document_id)
    if document.state == DocumentState.NEW:
        return redirect(url_for('document.upload_images_to_document', document_id=document.id))
    elif document.state == DocumentState.COMPLETED_LAYOUT_ANALYSIS:
        return redirect(url_for('layout_analysis.show_results', document_id=document.id))
    elif document.state != DocumentState.COMPLETED_OCR:
        flash(u'Document can not be edited in its current state.', 'danger')
        return redirect(url_for('main.index'))

    images = natsorted(get_document_images(document).all(), key=lambda x: x.filename)
    return render_template('ocr/ocr_results.html', document=document, images=images,
                           trusted_user=is_user_trusted(current_user), computed_scores=True, public_view=False)


@bp.route('/show_public_results/<string:document_id>', methods=['GET'])
@bp.route('/show_public_results/<string:document_id>/<string:image_id>', methods=['GET'])
@bp.route('/show_public_results/<string:document_id>/<string:image_id>/<string:line_id>', methods=['GET'])
def show_public_results(document_id, image_id=None, line_id=None):
    if not document_exists(document_id):
        flash(u'This document does not exist or it is not public at the moment!', 'danger')
        return redirect(url_for('document.public_documents'))

    document = get_document_by_id(document_id)
    if not document.is_public:
        flash(u'This document does not exist or it is not public at the moment!', 'danger')
        return redirect(url_for('document.public_documents'))

    if document.state != DocumentState.COMPLETED_OCR:
        flash(u'This public document has not been processed by OCR and it is not viewable.', 'danger')
        return redirect(url_for('document.public_documents'))

    images = natsorted(get_document_images(document).all(), key=lambda x: x.filename)
    return render_template('ocr/ocr_results.html', document=document, images=images,
                           trusted_user=False, computed_scores=True, public_view=True)

@bp.route('/show_results_new/<string:document_id>', methods=['GET'])
@bp.route('/show_results_new/<string:document_id>/<string:image_id>', methods=['GET'])
@bp.route('/show_results_new/<string:document_id>/<string:image_id>/<string:line_id>', methods=['GET'])
@login_required
def show_results_new(document_id, image_id=None, line_id=None):
    if not document_exists(document_id):
        flash(u'Document with this id does not exist!', 'danger')
        return redirect(url_for('main.index'))
    if not is_user_owner_or_collaborator(document_id, current_user):
        flash(u'You do not have sufficient rights to this document!', 'danger')
        return redirect(url_for('main.index'))

    document = get_document_by_id(document_id)
    if document.state == DocumentState.NEW:
        return redirect(url_for('document.upload_images_to_document', document_id=document.id))
    elif document.state == DocumentState.COMPLETED_LAYOUT_ANALYSIS:
        return redirect(url_for('layout_analysis.show_results_new', document_id=document.id))
    elif document.state != DocumentState.COMPLETED_OCR:
        flash(u'Document can not be edited int its current state.', 'danger')
        return redirect(url_for('main.index'))

    images = natsorted(get_document_images(document).all(), key=lambda x: x.filename)
    return render_template('ocr/ocr_results_new.html', document=document, images=images,
                           trusted_user=is_user_trusted(current_user), computed_scores=True)

@bp.route('/revert_ocr/<string:document_id>', methods=['GET'])
@login_required
def revert_ocr(document_id):
    if not is_user_owner_or_collaborator(document_id, current_user):
        flash(u'You do not have sufficient rights to this document!', 'danger')
        return redirect(url_for('main.index'))

    document = get_document_by_id(document_id)
    if document.state != DocumentState.COMPLETED_OCR:
        flash(u'Document is in the state prohibiting OCR revert!', 'danger')
        return redirect(url_for('main.index'))

    print()
    print("REVERT OCR")
    print("##################################################################")
    delete_user = db_session.query(User).filter(User.first_name == "#revert_OCR_backup#").first()
    backup_document = Document(name="revert_backup_" + document.name, state=DocumentState.COMPLETED_OCR,
                               user_id=delete_user.id, line_count=document.line_count,
                               annotated_line_count=document.annotated_line_count)
    db_session.add(backup_document)
    for original_img in document.images:
        backup_img = Image(id=uuid.uuid4(), filename=original_img.filename, path=original_img.path, width=original_img.width, height=original_img.height,
                           deleted=original_img.deleted, imagehash=original_img.imagehash)
        backup_document.images.append(backup_img)
        for region in original_img.textregions:
            region.image_id = backup_img.id
            original_img.textregions.append(
                TextRegion(order=region.order, points=region.points, deleted=region.deleted))
    document.state = DocumentState.COMPLETED_LAYOUT_ANALYSIS
    document.annotated_line_count = 0
    db_session.commit()
    print("##################################################################")
    return document_id


@bp.route('/create_edit_annotation', methods=['POST'])
@login_required
def create_edit_annotation():
    data = request.get_json()
    annotation = data['annotation']
    annotation_type = data['annotation_type']
    points = ' '.join(map(lambda p: f'{int(p["x"])},{int(p["y"])}', annotation['points']))
    baseline = None
    heights = None
    if annotation_type == 'row':
        baseline = ' '.join(map(lambda p: f'{int(p["x"])},{int(p["y"])}', annotation['baseline']))
        heights = f"{annotation['heights'][0]} {annotation['heights'][1]}"

    if annotation_type == 'row':
        text_line = get_text_line_by_id(annotation['uuid'])
        if text_line is not None:
            text_line.points = points
            text_line.baseline = baseline
            text_line.heights = heights
            db_session.commit()
            return 'edited', 200
    elif annotation_type == 'region':
        text_region = get_text_region_by_id(annotation['uuid'])
        if text_region is not None:
            text_region.points = points
            db_session.commit()
        return 'edited', 200
    else:
        return 'Unknown annotation type', 400


    insert_data = None
    if annotation_type == 'row':  # Row
        region_id = annotation['region_annotation_uuid']
        if not region_id:
            return 'Annotation does not exist and image_id is not set', 400
        insert_data = TextLine(

app/templates/ocr/ocr_results.html
{% extends "base/base.html" %}

{% block content %}
    <div class="container-fluid px-4 pb-0">

        <div class="row my-4">
              <div class="col-sm-8">
                <h3 class="text-left">Document name: {{ document.name }}</h3>
                <h3 id="document-id" style="display: None">{{ document.id }}</h3>
            </div>
            {% if not public_view %}
            <div class="col-sm-4 text-right" >
                {% include '/document/document_action_buttons.html' %}
            </div>
            {% endif %}
        </div>

        <!-- Image horizontal scroll bar -->
        <div class="row mb-4">
            <div class="col-sm-12">
                {% include 'base/scrolling_wrapper.html' %}
            </div>
        </div>

        <!-- Buttons -->
        <div class="row">
            <div class="col-lg-6 col-md-5">
                <button id="back-btn" type="button" class="btn btn-secondary mb-2" data-toggle="tooltip"
                        data-placement="top" title="ALT + LEFT"><i class="fas fa-arrow-left"></i>&nbsp;&nbsp;Back</button>
                <button id="next-btn" type="button" class="btn btn-secondary mb-2" data-toggle="tooltip"
                        data-placement="top" title="ALT + RIGHT">Next&nbsp;&nbsp;<i class="fas fa-arrow-right"></i></button>
            </div>
            {% if not public_view %}
            <div class="col-lg-6 col-md-7 text-md-right">
                <a id="btn-export-page-xml" class="btn btn-info mb-2" role="button"  download><i class="far fa-file-code fa-lg"></i>&nbsp;&nbsp;Export PAGE</a>
                <a id="btn-export-alto-xml" class="btn btn-info mb-2" role="button" download><i class="far fa-file-code fa-lg"></i>&nbsp;&nbsp;Export ALTO</a>
                <a id="btn-export-text" class="btn btn-info mb-2" role="button" download><i class="far fa-file-alt fa-lg"></i>&nbsp;&nbsp;Export TEXT</a>
                <a id="btn-export-img" class="btn btn-info mb-2" role="button" download><i class="far fa-file-image fa-lg"></i></i>&nbsp;&nbsp;Export IMAGE</a>
                {% if trusted_user == True %}
                    <a id="btn-compute-scores" class="btn btn-info mb-2" role="button" style="color:white">Compute scores</a>
                {% endif  %}
                {% if computed_scores == True %}
                    <a class="btn btn-info mb-2" role="button" style="color:white" href="/document/lines_check/{{ document.id }}">Show Suspect Lines</a>
                {% endif  %}
            </div>
            {% endif %}
        </div>

        <!-- Annotator -->
        <div class="row" id="annotator_type_0">
            <div class="col-sm-12">
                <div id="map-container">
                    <div class="editor-map" style="height: 500px">
                    </div>
                    <div class="status">
                    </div>
                </div>
                <p id="status"></p>
            </div>
        </div>

        <!-- Annotator Component -->
        <div class="row" id="annotator_component">
            <div class="col-12">
                <div id="app_app">
{#                    <annotator-wrapper-component ref="annotator_wrapper_component"></annotator-wrapper-component>#}
                </div>
            </div>
        </div>

        <!-- Text scroll editor -->
        <div class="row" id="text_scroll_editor">
            <div class="col-sm-12 text-center">
                <div id="text-container" style="height: 200px; overflow-y: auto;"></div>
            </div>
        </div>

        <!-- Buttons -->
        {% if not public_view %}
        <div class="row mt-2">
            <div class="col-sm-11 d-xl-none text-center">
                <button type="button" class="save-btn btn btn-success"><i class="far fa-save fa-lg"></i>Save</button>
            </div>
            <div class="col-sm-1 d-xl-none text-right">
                <button type="button" class="keyboard-btn btn btn-secondary" data-toggle="tooltip"
                        data-placement="top" title="ALT + K"><i class="far fa-keyboard fa-lg"></i></button>
            </div>
        </div>
        {% endif %}

        <div class="row my-2">
            <div class="col-xl-4">
                <div class="d-flex flex-row">
                    <div class="input-group pr-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="inputGroup-sizing-default">Height</span>
                        </div>
                        <input type="number" min="25" value="50" id="show-line-height" class="form-control" aria-label="Default" aria-describedby="inputGroup-sizing-default">
                    </div>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="inputGroup-sizing-default">Pad</span>
                        </div>
                        <input type="number" min="0" value="100" id="show-bottom-pad" class="form-control" aria-label="Default" aria-describedby="inputGroup-sizing-default">
                    </div>
                </div>
            </div>
            {% if not public_view %}
            <div class="col-xl-4 d-none d-xl-block text-center">
                <button type="button" data-toggle="tooltip" data-placement="top" title="ALT + V" class="save-btn btn btn-success"><i class="far fa-save fa-lg"></i>&nbsp;&nbsp;Save</button>
                <button type="button" data-toggle="tooltip" data-placement="top" title="ALT + B" id="deletebutton" class="btn btn-danger"><i class="far fa-trash-alt"></i> Delete line</button>
                <button type="button" data-toggle="tooltip" data-placement="top" title="ALT + N" id="ignorebutton" class="btn btn-info"><i class="fas fa-minus-circle"></i> Ignore line</button>
                <button type="button" data-toggle="tooltip" data-placement="top" title="ALT + M" id="nextsucpectline" class="btn btn-secondary">Next suspect line&nbsp;&nbsp;<i class="fas fa-arrow-right"></i></button>
            </div>
            <div class="col-xl-4 d-none d-xl-block text-right">
                <button type="button" class="keyboard-btn btn btn-secondary" data-toggle="tooltip"
                        data-placement="top" title="ALT + K"><i class="far fa-keyboard fa-lg"></i></button>
            </div>
            {% endif %}
        </div>
        {% if not public_view %}
        <div id="keyboard" class="d-none">
            <div class=" text-right pb-2">
                <button type="button" class="keyboard-btn btn btn-link"><i class="fas fa-times fa-lg"></i></i></button>
            </div>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <label class="input-group-text" for="layout-select">Layout</label>
                </div>
                <select class="custom-select" id="layout-select">
                </select>
            </div>
            <div id="layouts"></div>
            <div class="d-flex flex-row pt-4">
                <div class="input-group pr-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="new-letter">New letter</span>
                    </div>
                    <input type="text" maxlength="1"  id="new-letter-input" class="form-control" aria-label="Default" aria-describedby="new-letter">
                </div>
                <div id="add-new-letter-btn" class="btn btn-success mr-2">Add</div>
                <div id="remove-custom-letters-btn" class="btn btn-danger">Remove custom letters</div>
            </div>
        </div>
        {% endif %}

    </div>
{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="/static/annotator_component.css"/> <!-- Main css file -->
    <link rel="stylesheet" href="/static/leaflet/leaflet.css">
    <link rel="stylesheet" href="/static/css/ocr_results.css">
    <style>
    br {
        display: none;
    }
    </style>
{% endblock %}

{% block scripts %}
    <script src="{{ url_for('static', filename='js/lazy_image.js') + '?version=0.0.1' }}"></script>
    <script src="/static/annotator_component.js"></script> <!-- Main js file -->
    <script>
        function my_lazy_callback(element){
            let image_fetch = new Promise((resolve, reject) => {
                element.onload = resolve;
                element.onerror = reject;
                {% if not public_view %}
                    element.src  = element.dataset.src.replace('get_image_preview', 'get_image_preview');
                {% else %}
                    element.src  = element.dataset.src.replace('get_image_preview', 'get_public_image_preview');
                {% endif %}
            });
            let figure = element.parentElement;
            let state_fetch = fetch("/ocr/get_image_annotation_statistics/" + figure.dataset['image'])
                .then(response => response.json())
                .then(data => {
                    if(data['annotated_count'] == data['line_count']){
                        element.parentElement.style.backgroundColor = '#83d8f7';
                    } else if (data['annotated_count'] > 0){
                        element.parentElement.style.backgroundColor = '#faed8e';
                    }
                });
            return Promise.all([image_fetch, state_fetch]);
        }

        document.addEventListener("DOMContentLoaded",
            function () {
                manage_lazy_images(my_lazy_callback)
            });
    </script>
    <script>
        $(function () {
            $('[data-toggle="tooltip"]').tooltip()
        })
    </script>
    <script src="/static/leaflet/leaflet.js"></script>
    <script src="/static/leaflet/Leaflet.Editable.js"></script>
    <script src="/static/leaflet/Path.Drag.js"></script>
    <script src="/static/js/arabic_reshaper.js?version=1.4.21"></script>
    <script src="/static/js/ocr/ocr_export_buttons.js?version=1.4.3"></script>
    <script src="/static/js/ocr/text_line.js?version=1.4.27"></script>
    <script src="/static/js/ocr/text_lines_editor.js?version=1.4.26"></script>
    <script src="/static/js/ocr/keyboard.js?version=1.4.6"></script>
    <script src="/static/js/image_list.js?version=1.4.9"></script>
    <script>
        {% if public_view %}
            let public_view = true;
        {% else %}
            let public_view = false;
        {% endif %}



        let text_lines_editor = new TextLinesEditor(document.getElementById('map-container'), public_view);
        {% if public_view %}
            let image_list = new ImageList([text_lines_editor], 'show_public_results');
        {% else %}
            let ocr_export_buttons = new OCRExportButtons(public_view);
            let image_list = new ImageList([ocr_export_buttons, text_lines_editor], 'show_results');
            let keyboard = new Keyboard(document.getElementById('keyboard'), text_lines_editor);
        {% endif %}

        {% if not public_view %}
        document.querySelector('body').addEventListener('keydown', shortcut);
        function shortcut(e) {
            // ALT + V
            if (e.keyCode == 86 && !e.ctrlKey && !e.shiftKey && e.altKey)
            {
                e.preventDefault();
                text_lines_editor.save_annotations();
            }

            // ALT + B
            if (e.keyCode == 66 && !e.ctrlKey && !e.shiftKey && e.altKey)
            {
                e.preventDefault();
                text_lines_editor.delete_line_btn_action();
            }

            // ALT + N
            if (e.keyCode == 78 && !e.ctrlKey && !e.shiftKey && e.altKey)
            {
                e.preventDefault();
                text_lines_editor.ignore_line_btn_action(true);
            }

            // ALT + M
            if (e.keyCode == 77 && !e.ctrlKey && !e.shiftKey && e.altKey)
            {
                e.preventDefault();
                text_lines_editor.show_next_line();
            }
        }
        {% endif %}
    </script>
{% endblock %}

app/templates/ocr/ocr_training_documents.html
{% extends "base/base.html" %}

{% block styles %}
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css">
<link rel="stylesheet" href="/static/css/loader.css?v=1.0">
<style>
.document-action-btn{
    min-height: 25px;
}
input[type=checkbox] {
    transform: scale(2.5);
}
</style>
{% endblock %}

{% block content %}
    <form action="/ocr/ocr_training_documents">
        <label for="ocr_id">OCR ENGINE:</label>
        <select id="ocr" name="ocr" multiple>
            {% for ocr in all_ocr_engines %}
                <option value="{{ ocr.id }}">{{ocr.name}} {{ocr.active}}</option>
            {% endfor  %}
        </select>
        <input type="submit">
    </form>

    <div class="row">
        <div class="offset-xl-1 col-xl-10">
<table id="training_doc_table" class="table table-hover">
    <thead>
    <tr role="row">
        <th scope="col" class="image_column">Page</th>
        <th scope="col">Timestamp</th>
        <th scope="col">Name</th>
        <th scope="col">Owner</th>
        <th scope="col">Lines</th>
        <th scope="col">Revised</th>
        <th scope="col" >Model</th>
        {% for ocr in ocr_engines %}
            <th scope="col" id="selected_column">{{ocr.name}}</th>
        {% endfor %}
    </tr>
    </thead>
    <tbody>
    {% for document in documents %}
        <tr data-document="{{ document.id }}">
            <td data-sort="{{loop.index}}">
                <div class="image-preview-cont">
                    <img data-src="{{url_for('document.get_image_preview', image_id=previews[document.id].id)}}" class="lazy-img image-preview" src="" onerror="this.src='/static/img/missing_page.png'"/>
                </div>
            </td>
            {% if document.requests_lazy %}
                <td class="utc-time" data-sort="{{document.requests_lazy[-1].created_date.isoformat()}}">{{ document.requests_lazy[-1].created_date.isoformat() }}</td>
            {% else %}
                <td class="utc-time" data-sort="0">N/A</td>
            {% endif %}

            <td><a href="{{ url_for('ocr.show_results', document_id=document.id) }}">{{ document.name }}</a></td>
            <td>{{ document.user.first_name }} {{ document.user.last_name }}</td>

            <td>{{ document.line_count }}</td>
            <td>{{ document.annotated_line_count }}</td>

            {% if not document.requests_lazy or not document.requests_lazy[-1].ocr_id %}
                <td>N/A</td>
            {% else %}
                <td>{{ engine_names[document.requests_lazy[-1].ocr_id] }}</td>
            {% endif %}

            {% for ocr in ocr_engines %}
            <td id="{{document.id + ocr.id}}" data-sort="{{ document.id in selected_documents[ocr.id] }}">
                <input data-document_id="{{document.id}}" data-ocr_id="{{ocr.id}}" type="checkbox" {{ "checked" if document.id in selected_documents[ocr.id] }} />
            </td>
            {% endfor %}
        </tr>
    {% endfor %}
    </tbody>
</table>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script src="/static/js/select.js?version=1.1"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>
    <script src="{{ url_for('static', filename='js/lazy_image.js') + '?version=0.0.1' }}"></script>

    <script>
        for(var elem of document.getElementsByClassName("utc-time")){
            const date = new Date(elem.textContent + 'Z');
            elem.innerHTML = date.toLocaleString();
        }

        function template_set_url_callback(element){
            return new Promise((resolve, reject) => {
                element.onload = () => resolve();
                element.onerror = reject;
                element.src = element.dataset.src;
            });
        }

        document.addEventListener("DOMContentLoaded",
            function () {
                manage_lazy_images(template_set_url_callback);
            });

        $(document).ready(function () {
            // Setup table - add a text input to each footer cell
            let update_table = function() {
                let checkboxes = document.querySelectorAll("input[type=checkbox]");
                checkboxes.forEach((item, index, array) => {
                    item.onchange = function () {
                        let url = Flask.url_for('ocr.ocr_training_documents_post', {
                            document_id: this.dataset['document_id'],
                            ocr_id: this.dataset['ocr_id'],
                            state: $(this).prop('checked')
                        });
                        fetch(url).then(data => {
                            if (data.status > 400) {
                                alert('ERROR: Failed to set training document. ' + data.status);
                            }
                        }, error => alert('ERROR: Failed to set training document. ' + error));
                        if ($(this).prop('checked')) {
                            this.parentElement.dataset.sort = 'True';
                        } else {
                            this.parentElement.dataset.sort = 'False';
                        }
                        $('#training_doc_table').DataTable().cell("#" + this.dataset['document_id'] + this.dataset['ocr_id']).invalidate();
                    };
                });
            };

            $('#training_doc_table thead tr').clone(true).appendTo('#training_doc_table thead');
            let table = $('#training_doc_table').on('draw.dt', update_table).DataTable({
                stateSave: true,
                orderCellsTop: true,
                fixedHeader: true,
            });

            let state = table.state.loaded();
            $('#training_doc_table thead tr:eq(1) th').each(function (i) {
                let title = $(this).text();
                let input_value = '';
                try {
                    input_value = state.columns[i].search.search;
                } catch(err){
                    console.log('ERROR')
                }
                if (['Timestamp', 'Name', 'Owner', 'Model'].includes(title)) {
                    $(this).html('<input type="text" placeholder="Search"  value="' + input_value + '"/>');
                    $('input', this).on('keyup change', function () {
                        if (table.column(i).search() !== this.value) {
                            table.column(i).search(this.value).draw();
                        }
                    });
                } else {
                    $(this).html('');
                }
            });


        });
    </script>
{% endblock %}